### PR TITLE
Add support for root modules in config

### PR DESCRIPTION
**Pull request by LukeNeedham**
## 🚀 Description
Add the configuration option 'rootModulesRegex', which allows a user to specify the root module(s) which should be used in the generated dependency graph.

## 📄 Motivation and Context
The problem is that when you have many modules (say more than 30), the entire dependency graph is going to be massive and unreadable. It would be nice to have a way to say "generate the graph by starting at this root module, so the graph only includes modules that are dependencies either directly or transitively of the root module". This can help narrow the scope of the graph enormously, so that the graph only generates for the feature(s) you're interested in.

## 🧪 How Has This Been Tested?
Tested using the sample project manually, and wrote a new test class: ProjectParserRootModulesTest

In order to be able to write `ProjectParserRootModulesTest`, I had to make the graph parsing logic unit-testable. This required abstracting away the `org.gradle.api.Project` dependency from the parsing logic, and introducing a new `GradleProject` interface instead. `GradleProject` can be easily mocked in our unit tests.

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

The changes are backwards compatible - the default value of `rootModules` is null, which is handled in the same way as previously.

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### Examples

I ran the new plugin on the Tivi app to see how it performs on a large project:
https://github.com/chrisbanes/tivi

The results are attached in files below

[tivi - no root modules.txt](https://github.com/iurysza/module-graph/files/15211234/tivi.-.no.root.modules.txt)

[tivi - :ui:episode:details.txt](https://github.com/iurysza/module-graph/files/15211235/tivi.-.ui.episode.details.txt)

[tivi - :common:ui:resources:strings.txt](https://github.com/iurysza/module-graph/files/15211236/tivi.-.common.ui.resources.strings.txt)

[tivi - (:data:episodes)|(:core:powercontroller).txt](https://github.com/iurysza/module-graph/files/15211237/tivi.-.data.episodes.core.powercontroller.txt)

### CODE REVIEW

**Comment by iurysza** [comment]
Hey, thanks for the pr. I'll take a look at it over the weekend. Cheers!

**Comment by iurysza** [comment]
Hey, I've checked it out and everything seems solid! Specially abstracting away the Gradle stuff.  I've been dragging my feet on that refact, so thanks!

Can you take a look at the failing test plz? It seems we might have to tweak the module parsing.
Also, would you mind trying the feature on [TIVI](https://github.com/chrisbanes/tivi) and adding the output on the PR description?

You can publish it locally with: 
```bash
./gradlew :plugin-build:modulegraph:publishToMavenLocal
```

:v:

**Comment by LukeNeedham** [comment]
Hey, thanks for the review. I had a look at the failing test - turns out it had a circular Gradle dependency which the new parsing logic couldn't handle. The problem was that when we created a `GradleProjectImpl` instance for a Project, it would recursively create `GradleProjectImpl` instances for every dependency in that Project. And when there's a circular dependency, that's going to recurse infinitely. 

I couldn't find a nice way to solve this issue using `GradleProject`, so I've reworked the abstraction to  `ProjectQuerier` instead. This way we only query the data from the underlying `Project` instance when needed, which avoids the need to wrap everything into a wrapper class, which avoids needing to resolve all dependencies at once.

I also realised we don't need 2 separate functions for handling graphs with rootModules set, and those without. We now handle them both in the same way, which should now be fine because I added a check to avoid parsing the same project multiple times. In other words, if a graph doesn't set `rootModules` then every module is parsed as a root. It sounds expensive, but the new check ensures each project is only ever parsed once, so performance should be unchanged. 

After all these changes, I ran the plugin on Tivi. I've added the results to the description now!

**Comment by iurysza** [comment]
Hey, I took another look and tweaked a couple of small things. Overall it's great.

**Pull request merged**
